### ISSUE TITLE
How did you use the model for color images?

### ISSUE THREAD

**Issue by joeljosephjin** [kglore/llnet_color#4]

**Comment by kglore** [comment]
Oh my, I'm sorry I was not aware of these comments. I'm sorry! Will be responding to each issues now, even though we no longer maintain this repo actively.

Unlike the initial paper, the model is already designed to use for color images.
Since this is one of the first work using DL for low light enhancement (2016-2017 era), we are only vectorizing the channels and feeding it to a fully connected network and train it with SDA scheme and loss functions.
